# Generated by Django 4.1.2 on 2022-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
