# Generated by Django 4.1.2 on 2022-10-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_profile_age_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
